before_install: openssl aes-256-cbc -K $encrypted_ef7bff34d55e_key -iv $encrypted_ef7bff34d55e_iv -in github_deploy_key.enc -out github_deploy_key -d
language: node_js
node_js:
  - 9
script: npm run build
after_success:
  - MESSAGE=$(git log --format=%B -n 1 $TRAVIS_COMMIT)
  - git clone git://Ansaal/ansaal.github.io.git deploy
  - mv -f dist deploy
  - cd deploy
  - git remote
  - git config user.email jhulsch.jh@gmail.com
  - git config user.name Ansaal
  - git add -A
  - git commit -m Commit from Travis
  - git push "https://$github_deploy_key@Ansaal/ansaal.github.io" origin master
